portal:
    resource: "@PortalBundle/Controller/"
    type:     annotation
    prefix:   /portal
kvint:
    resource: "@KvintBundle/Controller/"
    type:     annotation
    prefix:   /kvint
app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
sg_datatables_bundle:
    resource: "@SgDatatablesBundle/Controller/"
    type:     annotation
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin